name: dpip
description: "Disaster Prevention Information Platform"
publish_to: 'none'
version: 3.0.013

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  autostarter: 0.0.2
  awesome_notifications: 0.10.1
  awesome_notifications_core: 0.10.1
  awesome_notifications_fcm: 0.10.1
  cached_network_image: ^3.4.1
  clipboard: 0.1.3
  collection: ^1.19.1
  device_info_plus: ^11.4.0
  disable_battery_optimization:
    git:
      url: https://github.com/pvsvamsi/Disable-Battery-Optimizations.git
      ref: 414b781
  dynamic_system_colors: ^1.8.0
  firebase_core: ^3.13.0
  firebase_messaging: 15.2.5
  fl_chart: ^0.71.0
  flex_color_picker: ^3.7.0
  flutter:
    sdk: flutter
  flutter_background_service:
    git:
      url: https://github.com/ExpTechTW/flutter_background_service.git
      path: packages/flutter_background_service
      ref: master
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  flutter_svg: ^2.1.0
  fluttertoast: 8.2.12
  freezed_annotation: ^3.0.0
  gal: ^2.3.0
  geolocator: ^14.0.0
  geolocator_android: ^5.0.1+1
  go_router: ^15.1.1
  http: ^1.3.0
  i18n_extension: ^15.0.5
  in_app_purchase: ^3.2.2
  in_app_update: 4.2.3
  intl: any
  json_annotation: 4.9.0
  maplibre_gl: 0.22.0
  material_symbols_icons: ^4.2815.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  simple_icons: ^14.6.1
  skeletonizer: ^2.0.0-pre
  styled_text: ^8.1.0
  talker_flutter: ^4.7.2
  timezone: ^0.10.0
  tutorial_coach_mark: ^1.3.0
  url_launcher: ^6.3.1
  ip_country_lookup: ^1.0.0
  flutter_icmp_ping: ^3.1.3

dependency_overrides:
  intl: 0.19.0

dev_dependencies:
  build_runner: 2.4.15
  flutter_test:
    sdk: flutter
  i18n_extension_importer: ^0.0.6
  in_app_purchase_platform_interface: ^1.4.0
  json_serializable: 6.9.5
  lint: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/translations/
  - assets/map/
  - assets/DPIP.png
  - assets/ExpTech.png
  - assets/location.json
  - assets/notify_test.json
  - assets/time.json
  - assets/box.json
  - assets/sprites.png
  - assets/sprites.json
