name: dpip
description: "Disaster Prevention Information Platform"
publish_to: 'none'
version: 2.1.504

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  autostarter: ^0.0.1
  cached_network_image: ^3.3.1
  clipboard: ^0.1.3
  collection: ^1.18.0
  cupertino_icons: 1.0.6
  device_info_plus: ^10.1.0
  disable_battery_optimization: ^1.1.1
  dynamic_color: ^1.7.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter_background_service:
    git:
      url: https://github.com/ExpTechTW/flutter_background_service.git
      path: packages/flutter_background_service
      ref: master
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  fluttertoast: ^8.2.6
  freezed_annotation: ^2.4.2
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  geolocator_android: ^4.6.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  image_gallery_saver:
    git:
      url: https://github.com/FlutterStudioIst/image_gallery_saver.git
  intl: any
  json_annotation: ^4.9.0
  maplibre_gl: ^0.20.0
  material_symbols_icons: ^4.2771.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  riverpod: ^2.0.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  simple_icons: ^10.1.3
  timezone: ^0.9.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/map/
    - assets/map/icons/
    - assets/DPIP.png
    - assets/location.json
    - assets/time.json
    - assets/box.json
    - assets/eew.wav
    - assets/eew_alert.wav
    - assets/eq.wav
    - assets/info.wav
    - assets/int_report.wav
    - assets/normal.wav
    - assets/rain.wav
    - assets/report.wav
    - assets/tsunami.wav
    - assets/update.wav
    - assets/warn.wav
    - assets/weather.wav
