name: dpip
description: "Disaster Prevention Information Platform"
publish_to: "none"
version: 3.2.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

platforms:
  android:
  ios:

dependencies:
  android_alarm_manager_plus:
    git:
      url: https://github.com/ExpTechTW/plus_plugins.git
      path: packages/android_alarm_manager_plus
      ref: 81fc434
  async: ^2.13.0
  awesome_notifications: 0.10.1
  awesome_notifications_fcm: 0.10.1
  cached_network_image: ^3.4.1
  clipboard: ^3.0.8
  collection: ^1.19.1
  crypto: ^3.0.7
  device_info_plus: ^12.3.0
  disable_battery_optimization:
    git:
      url: https://github.com/ExpTechTW/Disable-Battery-Optimizations.git
      ref: 2addde3
  dynamic_color: ^1.8.1
  firebase_core: 3.15.2 #4.0.0 升級最低支援iOS 15
  firebase_messaging: 15.2.10
  flex_color_picker: ^3.8.0
  flutter_compass: ^0.8.1
  flutter:
    sdk: flutter
  flutter_icmp_ping:
    git:
      url: https://github.com/ExpTechTW/flutter_icmp_ping.git
      ref: 6b9daff
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  fluttertoast: ^9.0.0
  freezed_annotation: ^3.1.0
  gal: ^2.3.2
  geojson_vi: ^2.2.5
  geolocator: ^14.0.2
  geolocator_android: ^5.0.2
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  html_unescape: ^2.0.0
  http: ^1.6.0
  i18n_extension: ^15.1.0
  in_app_purchase: ^3.2.3
  in_app_update: ^4.2.5
  intl: ^0.20.2
  ip_country_lookup: ^1.0.3
  json_annotation: ^4.9.0
  m3e_collection: ^0.3.7
  maplibre_gl: ^0.24.1
  markdown_widget: ^2.3.2+8
  material_symbols_icons: ^4.2892.0
  option_result: ^3.2.1
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.4
  simple_icons: ^14.6.1
  skeletonizer: ^2.1.2
  styled_text: ^8.1.0
  talker_flutter: ^5.1.9
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  zstandard: ^1.3.29

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.1.3
  i18n_extension_importer: ^0.0.6
  in_app_purchase_platform_interface: ^1.4.0
  json_serializable: ^6.11.3
  lint: ^2.8.0

flutter:
  uses-material-design: true
  shaders:
    - shaders/fog.frag
    - shaders/thunderstorm.frag
  assets:
    # localizations
    - assets/translations/
    # other
    - assets/map/
    - assets/wallpaper/day/
    - assets/wallpaper/dusk/
    - assets/wallpaper/night/
    - assets/DPIP.png
    - assets/ExpTech.png
    - assets/box.json
    - assets/location.json.gz
    - assets/notify_test.json
    - assets/time.json.gz
