name: dpip
description: "Disaster Prevention Information Platform"
publish_to: 'none'
version: 2.5.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  autostarter: ^0.0.2
  awesome_notifications_core: ^0.9.3
  awesome_notifications: ^0.9.3+1
  awesome_notifications_fcm: ^0.9.3+1
  cached_network_image: ^3.3.1
  clipboard: ^0.1.3
  collection: ^1.18.0
  device_info_plus: ^10.1.0
  disable_battery_optimization: ^1.1.1
  dynamic_color: ^1.7.0
  firebase_core: ^2.32.0
  firebase_messaging: 14.9.4
  flutter_background_service:
    git:
      url: https://github.com/ExpTechTW/flutter_background_service.git
      path: packages/flutter_background_service
      ref: master
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_markdown: ^0.7.3+1
  fluttertoast: ^8.2.6
  freezed_annotation: ^2.4.2
  geolocator: ^12.0.0
  geolocator_android: ^4.6.1
  http: ^1.2.1
  in_app_update: ^4.2.3
  image_gallery_saver:
    git:
      url: https://github.com/FlutterStudioIst/image_gallery_saver.git
  intl: any
  json_annotation: ^4.9.0
  maplibre_gl: ^0.20.0
  material_symbols_icons: ^4.2771.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  simple_icons: ^10.1.3
  talker_flutter: ^3.6.0
  timezone: ^0.9.3
  url_launcher: ^6.3.0
  tutorial_coach_mark: ^1.2.11
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/map/
  - assets/map/icons/
  - assets/DPIP.png
  - assets/ExpTech.png
  - assets/location.json
  - assets/notify_test.json
  - assets/time.json
  - assets/box.json
