name: dpip
description: Disaster Prevention Information Platform
publish_to: "none"

version: 1.1.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.2.1
  package_info_plus: ^6.0.0
  markdown_widget: ^2.2.0
  url_launcher: ^6.1.12
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.0
  firebase_analytics: ^10.10.0
  flutter_local_notifications: ^17.0.0
  clipboard: ^0.1.3
  connectivity_plus: ^6.0.1
  intl: ^0.18.1
  audioplayers: ^5.2.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  json_annotation: ^4.8.1
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/region.json
    - assets/eew_alert.wav
    - assets/eew_warn.wav
    - assets/warn.wav
