name: dpip
description: Disaster Prevention Information Platform
publish_to: "none"

version: 1.2.4

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^1.2.1
  package_info_plus: ^8.0.0
  markdown_widget: ^2.2.0
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.2
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.0
  flutter_local_notifications: ^17.0.1
  clipboard: ^0.1.3
  connectivity_plus: ^6.0.3
  intl: ^0.18.1
  audioplayers: ^5.2.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  json_annotation: ^4.8.1
  dynamic_color: ^1.7.0
  in_app_update: ^4.2.2
  app_settings: ^5.1.1
  simple_icons: ^10.1.3
  timezone: ^0.9.2
  material_symbols_icons: ^4.2719.3
  path_provider: ^2.1.3
  fluttertoast: ^8.2.5
  flutter_map_geojson: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/cross.png
    - assets/dist_code.json
    - assets/region.json
    - assets/eew_alert.wav
    - assets/eew_warn.wav
    - assets/eq.wav
    - assets/normal.wav
    - assets/rain.wav
    - assets/report.wav
    - assets/warn.wav
    - assets/weather.wav
    - assets/tw_city.geojson
    - assets/tsunami.wav
    - assets/info.wav