name: dpip
description: "Disaster Prevention Information Platform"
publish_to: "none"
version: 3.1.3

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.7"

dependencies:
  android_alarm_manager_plus:
    git:
      url: https://github.com/ExpTechTW/plus_plugins.git
      path: packages/android_alarm_manager_plus
      ref: 81fc434
  async: ^2.13.0
  awesome_notifications: 0.10.1
  awesome_notifications_fcm: 0.10.1
  cached_network_image: ^3.4.1
  clipboard: 2.0.2
  collection: ^1.19.1
  crypto: ^3.0.6
  device_info_plus: ^12.2.0
  disable_battery_optimization:
    git:
      url: https://github.com/ExpTechTW/Disable-Battery-Optimizations.git
      ref: 2addde3
  dynamic_system_colors: ^1.8.0
  firebase_core: 3.15.2 #4.0.0 升級最低支援iOS 15
  firebase_messaging: 15.2.10
  fl_chart: ^1.1.1
  flex_color_picker: ^3.7.1
  flutter:
    sdk: flutter
  flutter_icmp_ping:
    git:
      url: https://github.com/ExpTechTW/flutter_icmp_ping.git
      ref: 6b9daff
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  fluttertoast: ^9.0.0
  freezed_annotation: ^3.0.0
  gal: ^2.3.2
  geojson_vi: ^2.2.5
  geolocator: ^14.0.0
  geolocator_android: ^5.0.1+1
  go_router: ^17.0.0
  http: ^1.5.0
  i18n_extension: ^15.0.5
  in_app_purchase: ^3.2.2
  in_app_update: ^4.2.0
  intl: ^0.20.2
  ip_country_lookup: ^1.0.0
  json_annotation: 4.9.0
  maplibre_gl: ^0.24.1
  material_symbols_icons: ^4.2815.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  simple_icons: ^14.6.1
  skeletonizer: ^2.0.0-pre
  styled_text: ^8.1.0
  talker_flutter: ^5.0.2
  timezone: ^0.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.10.0
  flutter_test:
    sdk: flutter
  i18n_extension_importer: ^0.0.6
  in_app_purchase_platform_interface: ^1.4.0
  json_serializable: ^6.11.0
  lint: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # localizations
    - assets/translations/
    # other
    - assets/map/
    - assets/DPIP.png
    - assets/ExpTech.png
    - assets/box.json
    - assets/location.json.gz
    - assets/notify_test.json
    - assets/time.json.gz
