name: dpip
description: "Disaster Prevention Information Platform"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  json_annotation: ^4.9.0
  material_symbols_icons: ^4.2762.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  timezone: ^0.9.3
  flutter_background_service: ^5.0.6
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  # 目前geolocator_android 4.6有問題，故鎖定在4.5.5
  geolocator_android: 4.5.5
  flutter_localizations:
    sdk: flutter
  intl: any
  dynamic_color: ^1.7.0
  simple_icons: ^10.1.3
  url_launcher: ^6.3.0
  flutter_map: 6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/DPIP.png
  