name: dpip
description: A new Flutter project.
publish_to: 'none'

version: 1.0.15

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  http: ^1.1.0
  package_info_plus: ^4.1.0
  markdown_widget: ^2.2.0
  url_launcher: ^6.1.12
  cupertino_icons: ^1.0.2
  flutter_map: ^5.0.0
  flutter_map_geojson: ^1.0.3
  latlong2: ^0.9.0
  firebase_messaging: ^14.6.8
  firebase_core: ^2.16.0
  flutter_local_notifications: ^15.1.1
  clipboard: ^0.1.3
  connectivity_plus: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/region.json