name: Crowdin Action

on:
  push:
    branches: [ main,Crowdin-Action ]

jobs:
  crowdinup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          upload_sources_args: -b main --preserve-hierarchy
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  crowdin:
    needs: crowdinup
    name: Synchronize with Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Matrix
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          commit_message: New Crowdin translations
          localization_branch_name: l10n_main
          download_translations_args: -b main --preserve-hierarchyｓ

          create_pull_request: true
          pull_request_title: New translations
          pull_request_body: New Crowdin pull request
          pull_request_base_branch_name: 'main'

          pull_request_labels: 'enhancement, good first issue'
          pull_request_assignees: 'crowdin-bot'
          pull_request_reviewers: 'crowdin-user-reviewer'
          pull_request_team_reviewers: 'crowdin-team-reviewer'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
  # crowdin:
  #   needs: crowdinup
  #   name: Synchronize with Crowdin (${{ matrix.language.lc }})
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: false
  #     max-parallel: 1 # Should be 1 to avoid parallel builds
  #     matrix:
  #       language:
  #         - { lc: 'en', ln: 'English' }
  #         - { lc: 'ja', ln: 'Japanese' }
  #         - { lc: 'ko', ln: 'Korean' }
  #         - { lc: 'ru', ln: 'Russian' }
  #         - { lc: 'vi', ln: 'Vietnamese' }
  #         - { lc: 'zh-CN', ln: 'Chinese Simplified' }
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Matrix
  #       uses: crowdin/github-action@v2
  #       with:
  #         upload_sources: false
  #         upload_translations: false
  #         download_translations: true
  #         commit_message: New Crowdin translations - ${{ matrix.language.ln }}
  #         localization_branch_name: l10n_main_${{ matrix.language.lc }}
  #         download_language: ${{ matrix.language.lc }}
  #         download_translations_args: -b main --preserve-hierarchyｓ

  #         create_pull_request: true
  #         pull_request_title: New translations - ${{ matrix.language.ln }}
  #         pull_request_body: New Crowdin pull request with - ${{ matrix.language.ln }}
  #         pull_request_base_branch_name: 'main'

  #         pull_request_labels: 'enhancement, good first issue'
  #         pull_request_assignees: 'crowdin-bot'
  #         pull_request_reviewers: 'crowdin-user-reviewer'
  #         pull_request_team_reviewers: 'crowdin-team-reviewer'
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  #         CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}